import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from 'src/app/services/api/api.service';

@Component({
  selector: 'app-admin-navbar',
  templateUrl: './admin-navbar.component.html',
  styleUrls: ['./admin-navbar.component.scss']
})
export class AdminNavbarComponent {
  title = 'rms';
  public  data:any
//   =[
//     {
//         "id": 1,
//         "enrolmentNo": "NBAI1001",
//         "fullName": "ajay",
//         "dob": "2000-12-23",
//         "mobileNo": "12333",
//         "adharNo": "999999999999",
//         "formFillOrNot": true,
//         "approvalStatus": false,
//         "fatherName": "ajay f",
//         "fatherNo": "23444",
//         "fatherOccupation": "occu",
//         "presentAddress": "present",
//         "presentCity": "pres city",
//         "presentPin": 23444,
//         "presentState": "pres state",
//         "permanentAddress": "per ad",
//         "permanentCity": "per city",
//         "permanentPin": 34344,
//         "permanentState": "per state",
//         "religion": "rei",
//         "caste": "cast",
//         "academicStartYear": "2021",
//         "academicEndYear": "2024",
//         "referenceName": "ref name",
//         "referenceOccupation": "erf oc",
//         "referenceRelationship": "rel",
//         "referenceResidentialAddress": "resid",
//         "referenceMobileNo": "23434234",
//         "date": "2021-12-23",
//         "residencePlace": "resid place",
//         "photoName": "NBAI1001_6d40224a-e3da-4be1-aa2f-253415b19b6b",
//         "photoData": "",
//         "education": [
//             {
//                 "id": 1,
//                 "secondaryName": "St. Xavier's High School 1",
//                 "secondarymarksOrGrade": "85%",
//                 "secondaryyear": "2015",
//                 "secondaryBoard": "CBSE",
//                 "secondaryGradeType": "percentage",
//                 "seniorSecondaryName": "XYZ Senior Secondary School",
//                 "seniorSecondaryMarksOrGrade": "90%",
//                 "seniorSecondaryYear": "2017",
//                 "seniorSecondaryBoard": "CBSE",
//                 "seniorSecondaryGradeType": "percentage",
//                 "graduationName": "B.Sc in Computer Science",
//                 "graduationMarksOrGrade": "88%",
//                 "graduationYear": "2021",
//                 "graduationBoard": "University of Mumbai",
//                 "graduationGradeType": "percentage",
//                 "postGraduationName": "M.Sc in Computer Science",
//                 "postGraduationMarksOrGrade": "85%",
//                 "postGraduationYear": "2023",
//                 "postGraduationBoard": "post graduation college name",
//                 "postGraduationGradeType": "University of Mumbai"
//             }
//         ],
//         "email": "taha.khan@example.com"
//     },
//     {
//         "id": 6,
//         "enrolmentNo": "NBAI1009",
//         "fullName": "ajay3 narang",
//         "dob": "1153852200000",
//         "mobileNo": "2344",
//         "adharNo": "ajay3adhar",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "ajay4@gmail.com"
//     },
//     {
//         "id": 7,
//         "enrolmentNo": "NBAI1011",
//         "fullName": "ajay3 narang",
//         "dob": "1153852200000",
//         "mobileNo": "2344",
//         "adharNo": "ajay3adhar",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "ajay5@gmail.com"
//     },
//     {
//         "id": 8,
//         "enrolmentNo": "NBAI1012",
//         "fullName": "ajay6 narang",
//         "dob": "1721845800000",
//         "mobileNo": "234",
//         "adharNo": "ajay6adhar",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "ajay6@gmail.com"
//     },
//     {
//         "id": 9,
//         "enrolmentNo": "NBAI1014",
//         "fullName": "arvind rathore",
//         "dob": "2024-07-25",
//         "mobileNo": "234",
//         "adharNo": "7777-4444-77779",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "arvind1@gmail.com"
//     },
//     {
//         "id": 10,
//         "enrolmentNo": "NBAI1015",
//         "fullName": "arvind rathore",
//         "dob": "2024-07-25",
//         "mobileNo": "234",
//         "adharNo": "7777-4444-7777",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "arvind2@gmail.com"
//     },
//     {
//         "id": 11,
//         "enrolmentNo": "NBAI1016",
//         "fullName": "imran syed",
//         "dob": "2000-07-25",
//         "mobileNo": "9826506622",
//         "adharNo": "1234-1234-1234",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "tg.asct@gmail.com"
//     },
//     {
//         "id": 12,
//         "enrolmentNo": "NBAI1004",
//         "fullName": "furqan",
//         "dob": "2000-07-19",
//         "mobileNo": "7354137839",
//         "adharNo": "2855-6666-6666",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "furqank095@gmail.com"
//     },
//     {
//         "id": 13,
//         "enrolmentNo": "NBAI1005",
//         "fullName": "Anas",
//         "dob": "2011-07-05",
//         "mobileNo": "8797897897",
//         "adharNo": "678678678678",
//         "formFillOrNot": true,
//         "approvalStatus": false,
//         "fatherName": "jhjkhkjh",
//         "fatherNo": "7897897897",
//         "fatherOccupation": "bmnbmn",
//         "presentAddress": "uybjjk",
//         "presentCity": "hhjkh",
//         "presentPin": 878897,
//         "presentState": "hjkhjkh",
//         "permanentAddress": "jkhkhkjh",
//         "permanentCity": "jhkjhjk",
//         "permanentPin": 879879,
//         "permanentState": "jjgg",
//         "religion": "jhgjkgjh",
//         "caste": "gjgjh",
//         "academicStartYear": "2006",
//         "academicEndYear": "2046",
//         "referenceName": "jhjkhjkh",
//         "referenceOccupation": "hjkhjkh",
//         "referenceRelationship": "jhjkhjk",
//         "referenceResidentialAddress": "hjkhjkh",
//         "referenceMobileNo": "7889789789",
//         "date": "2024-07-29",
//         "residencePlace": "hjhjkh",
//         "photoName": "NBAI1005_pass.jpg",
//         "photoData": "",
//         "education": [],
//         "email": "Amerogol@gmail.com"
//     },
//     {
//         "id": 14,
//         "enrolmentNo": "NBAI1007",
//         "fullName": "muttu",
//         "dob": "2010-01-04",
//         "mobileNo": "7675765675",
//         "adharNo": "231243254354",
//         "formFillOrNot": false,
//         "approvalStatus": false,
//         "fatherName": null,
//         "fatherNo": null,
//         "fatherOccupation": null,
//         "presentAddress": null,
//         "presentCity": null,
//         "presentPin": 0,
//         "presentState": null,
//         "permanentAddress": null,
//         "permanentCity": null,
//         "permanentPin": 0,
//         "permanentState": null,
//         "religion": null,
//         "caste": null,
//         "academicStartYear": null,
//         "academicEndYear": null,
//         "referenceName": null,
//         "referenceOccupation": null,
//         "referenceRelationship": null,
//         "referenceResidentialAddress": null,
//         "referenceMobileNo": null,
//         "date": null,
//         "residencePlace": null,
//         "photoName": null,
//         "photoData": null,
//         "education": [],
//         "email": "mustufa877@gmail.com"
//     },
//     {
//         "id": 15,
//         "enrolmentNo": "NBAI1013",
//         "fullName": "mutyug",
//         "dob": "2011-07-05",
//         "mobileNo": "8788789789",
//         "adharNo": "877989689678",
//         "formFillOrNot": true,
//         "approvalStatus": false,
//         "fatherName": "ijioj",
//         "fatherNo": "8978978978",
//         "fatherOccupation": "hjkhjkh",
//         "presentAddress": "hjkhjk",
//         "presentCity": "Bagra",
//         "presentPin": 768686,
//         "presentState": "JH",
//         "permanentAddress": "jijoijo",
//         "permanentCity": "Daman District",
//         "permanentPin": 767867,
//         "permanentState": "DH",
//         "religion": "Islam",
//         "caste": "Sunni",
//         "academicStartYear": "2024",
//         "academicEndYear": "2005",
//         "referenceName": "jlh",
//         "referenceOccupation": "khkjhjkh",
//         "referenceRelationship": "jhkjh",
//         "referenceResidentialAddress": "hjkhk",
//         "referenceMobileNo": "7889789789",
//         "date": "2024-07-11",
//         "residencePlace": "jhkjhkjhkjhkjh",
//         "photoName": "NBAI1013_pass.jpg",
//         "photoData": "",
//         "education": [
//             {
//                 "id": 2,
//                 "secondaryName": "yuiyuiyuiy",
//                 "secondarymarksOrGrade": "56",
//                 "secondaryyear": "2023",
//                 "secondaryBoard": "mp",
//                 "secondaryGradeType": "percentage",
//                 "seniorSecondaryName": "",
//                 "seniorSecondaryMarksOrGrade": "",
//                 "seniorSecondaryYear": "",
//                 "seniorSecondaryBoard": "",
//                 "seniorSecondaryGradeType": "",
//                 "graduationName": "",
//                 "graduationMarksOrGrade": "",
//                 "graduationYear": "",
//                 "graduationBoard": "",
//                 "graduationGradeType": "",
//                 "postGraduationName": "",
//                 "postGraduationMarksOrGrade": "",
//                 "postGraduationYear": "",
//                 "postGraduationBoard": "",
//                 "postGraduationGradeType": ""
//             }
//         ],
//         "email": "syedmustufa877@gmail.com"
//     }
// ]
showData:boolean=false;

// showData: boolean = false;
showUserList: boolean = false;

constructor(private router: Router, private api :ApiService) {}

public logout() {
  localStorage.clear();
  this.router.navigate(['auth']);
}

navigateToUpdate(id:any){
  this.showUserList=!this.showUserList;
  this.router.navigate(['admin/admin-update-student/'+id])
}

// ngOnInit() {
//   this.api.getStudent().subscribe((successResponse:any)=>{
// console.log(successResponse)
// let successRe=successResponse.filter((res:any)=>{
//   if(successResponse?.formFillOrNot == true &&successResponse?.approvalStatus== false ){
//     return res
//   }

// })
// console.log(successRe)
//   },((errorResponse)=>{
//     console.log(errorResponse);
//   }))
// }
ngOnInit() {
  this.api.getStudent().subscribe((successResponse: any) => {
    console.log(successResponse);
    let filteredResponse = successResponse.filter((res: any) => {
      return res?.formFillOrNot === true && res?.approvalStatus === false;
    });
    console.log(filteredResponse);
    this.data=filteredResponse
  }, (errorResponse) => {
    console.log(errorResponse);
  });
}


toggle() {
  this.showUserList=!this.showUserList;
}

toggleUserList() {
  this.showUserList = !this.showUserList;
  console.log(this.showUserList);
}

}
